### ISSUE TITLE
Test failure: types::HexNumber is failing on fedora arch i686

### ISSUE THREAD

**Issue by jordalgo** [mich101mich/sscanf#10]
When adding sscanf as a fedora package, I had to disable this test because it failing on arch i686.

Build log:
https://kojipkgs.fedoraproject.org//work/tasks/8219/110718219/build.log
https://koji.fedoraproject.org/koji/taskinfo?taskID=110718219

Failure:
```
test src/types.rs - types::HexNumber (line 67) ... FAILED
test src/regex_representation.rs - regex_representation::RegexRepresentation (line 62) ... ok
failures:
---- src/types.rs - types::HexNumber (line 67) stdout ----
warning: use of deprecated struct `sscanf::HexNumber`: use "{:x}" with the desired number type instead
 --> src/types.rs:71:40
  |
7 | let output = sscanf!(input, "{} + {}", HexNumber, HexNumber).unwrap();
  |                                        ^^^^^^^^^
  |
  = note: `#[warn(deprecated)]` on by default
warning: use of deprecated struct `sscanf::HexNumber`: use "{:x}" with the desired number type instead
 --> src/types.rs:71:51
  |
7 | let output = sscanf!(input, "{} + {}", HexNumber, HexNumber).unwrap();
  |                                                   ^^^^^^^^^
error: literal out of range for `usize`
 --> src/types.rs:73:22
  |
9 | assert_eq!(output.1, 0x123456789abcdef);
  |                      ^^^^^^^^^^^^^^^^^
  |
  = note: the literal `0x123456789abcdef` (decimal `81985529216486895`) does not fit into the type `usize` and will become `2309737967usize`
  = note: `#[deny(overflowing_literals)]` on by default
```

rust2rpm spec file: https://jordalgo.fedorapeople.org/review/rust-sscanf/rust-sscanf.spec

**Comment by mich101mich** [comment]
Seems like that test assumes `usize == u64`. I have fixed this for the current dev branch, which will eventually be released with the next version.

I don't plan on releasing a new version for this yet as it only affects the unit tests of a deprecated component. The crate itself should already be platform-independent. Unless you need this to be a separate version?

**Comment by jordalgo** [comment]
@mich101mich Thanks for the quick response! No separate version needed if this is only affecting a unit test and fixed on dev.
