### ISSUE TITLE
Is that possible to support impl custom type by a format str used in scanf?

### ISSUE THREAD

**Issue by Luffbee** [mich101mich/sscanf#6]
A helper macro like scanf_get_regex to generate RegexRepresentation::REGEX by a format string will be really useful.

**Comment by Luffbee** [comment]
Thanks for your help. This can solve my problem, but I think it will be more friendly to write something like:
``` rust
impl RegexRepresentation for YourType {
    const REGEX: &'static str = scanf_get_regex_representation!("...{usize}...{:/[a-z]+}");
}
```
Some immature thoughts: in my case, `FromStr` is also implemented by `scanf!`, so a trait to auto implement `RegexRepresentation` and `FromStr` for this case will make custom type implementation much easier, something like (the `FromTuple` trait seems a problem here):
``` rust
impl Scanable for CustomType {
    const FORMAT: &'static str = "...{usize}...{:/[a-z]+}";
}
impl FromTuple for CustomType {
    fn from_tuple(...) {
    // construct from the result of scanf!
    }
}
impl<T> RegexRepresentation for T where T: Scanable + FromTuple {
    const REGEX: &'static str = scanf_get_regex_representation(T::FORMAT);
}
impl<T> std::str::FromStr for T where T: Scanable + FromTuple {
    fn from_str(s:&str) -> Result<Self, Self::Err> {
        Ok(T::from_tuple(scanf!(T::FORMAT)?));
    }
}
```
Thanks for your help again.

**Comment by mich101mich** [comment]
I have thought about doing something similar with derive, but custom helper traits could also work. The problem with all of this is that it goes way beyond what Procedural Macros can do, so it would have to rely on nightly const fn stuff or slow runtime parsing.

If I am going to do something like this, I would probably rework RegexRepresentation in general to allow more complex types with less effort, but that would be a huge breaking change.

**Comment by mich101mich** [comment]
The derive macro is added in version 0.4.0-alpha, allowing for code like:

```rust
#[derive(sscanf::FromScanf)]
#[sscanf(format = "...{some_number}...{some_text:/[a-z]+/}")]
struct CustomType {
    some_number: usize,
    some_text: String,
}
```
which automatically creates the `RegexRepresentation` and `FromScanf` (more specific version of `FromStr`) impls for `CustomType`.
